### ISSUE TITLE
Upgrade application to API version 20.4

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-comparison/GroupDocs.Comparison-for-Java-Spring#29]
Hi,
https://forum.groupdocs.com/t/groupdocs-total-license-is-not-valid/8807/6
Can you please upgrade the application to API version 20.4?

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

API version was bumped to 20.4, please checkout latest commit from master branch.

Regards
