### ISSUE TITLE
Pdf comparison is broken

### ISSUE THREAD

**Issue by pricewatermouse** [groupdocs-comparison/GroupDocs.Comparison-for-Java-Spring#31]
I am trying to compare a pair of pdf documents using both pre-built (comparison-spring-1.9.19.jar) and current docker version and get the error: "Something went wrong". I tryed a few pdfs, including really simple ones (single page, plain text, no pictures), but no one worked. Could you plase check?

The stack trace follows below:
`
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is class com.groupdocs.comparison.pdf.comparisonpdfexception.CreateResultDocumentException: PdfCompareResult.CrateDocumentComparison cannot create result document. Not enougher space for all components ---> class com.groupdocs.comparison.internal.c.a.pd.internal.ms.System.lh: At most 4 text fragments can be added in evaluation mode. com.groupdocs.comparison.internal.c.a.pd.TextBuilder.lI(Unknown Source) com.groupdocs.comparison.internal.c.a.pd.TextBuilder.appendParagraph(Unknown Source) com.groupdocs.comparison.internal.c.a.pd.TextBuilder.appendParagraph(Unknown Source) com.groupdocs.comparison.pdf.e.f.a(Unknown Source) com.groupdocs.comparison.pdf.e.b.a(Unknown Source) com.groupdocs.comparison.pdf.b.a.jq(Unknown Source) com.groupdocs.comparison.pdf.b.a.<init>(Unknown Source) com.groupdocs.comparison.pdf.j.a(Unknown Source) com.groupdocs.comparison.Comparer.a(Unknown Source) com.groupdocs.comparison.Comparer.compare(Unknown Source) com.groupdocs.ui.comparison.ComparisonServiceImpl.compareFiles(ComparisonServiceImpl.java:354) com.groupdocs.ui.comparison.ComparisonServiceImpl.compare(ComparisonServiceImpl.java:156) com.groupdocs.ui.comparison.ComparisonController.compare(ComparisonController.java:138) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) java.lang.reflect.Method.invoke(Unknown Source) org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) javax.servlet.http.HttpServlet.service(HttpServlet.java:707) org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) javax.servlet.http.HttpServlet.service(HttpServlet.java:790) org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317) org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219) org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) org.eclipse.jetty.server.Server.handle(Server.java:531) org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) java.lang.Thread.run(Unknown Source) --- End of inner exception stack trace --- com.groupdocs.comparison.pdf.b.a.jq(Unknown Source) com.groupdocs.comparison.pdf.b.a.<init>(Unknown Source) com.groupdocs.comparison.pdf.j.a(Unknown Source) com.groupdocs.comparison.Comparer.a(Unknown Source) com.groupdocs.comparison.Comparer.compare(Unknown Source) com.groupdocs.ui.comparison.ComparisonServiceImpl.compareFiles(ComparisonServiceImpl.java:354) com.groupdocs.ui.comparison.ComparisonServiceImpl.compare(ComparisonServiceImpl.java:156) com.groupdocs.ui.comparison.ComparisonController.compare(ComparisonController.java:138) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) java.lang.reflect.Method.invoke(Unknown Source) org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) javax.servlet.http.HttpServlet.service(HttpServlet.java:707) org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) javax.servlet.http.HttpServlet.service(HttpServlet.java:790) org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317) org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219) org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) org.eclipse.jetty.server.Server.handle(Server.java:531) org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) java.lang.Thread.run(Unknown Source)`

P.S. The host has enough RAM and disk space.

**Comment by liosha2007** [comment]
You have used file with more than 4 elements in it's structure. Unlicensed Comparison has limitations about it. Despite the fact that you used simple file, we can't be sure that it was created as simpe in it's structure. So, to solve the problem you can use valid Comparison license or try to create simple test file in another way.
